package com.yctxkj.blog.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseArticleCategory<M extends BaseArticleCategory<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
		return (M)this;
	}

	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

	public M setOrders(java.lang.Integer orders) {
		set("orders", orders);
		return (M)this;
	}

	public java.lang.Integer getOrders() {
		return get("orders");
	}

	public M setGrade(java.lang.Integer grade) {
		set("grade", grade);
		return (M)this;
	}

	public java.lang.Integer getGrade() {
		return get("grade");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return get("name");
	}

	public M setSeoDescription(java.lang.String seoDescription) {
		set("seo_description", seoDescription);
		return (M)this;
	}

	public java.lang.String getSeoDescription() {
		return get("seo_description");
	}

	public M setSeoKeywords(java.lang.String seoKeywords) {
		set("seo_keywords", seoKeywords);
		return (M)this;
	}

	public java.lang.String getSeoKeywords() {
		return get("seo_keywords");
	}

	public M setSeoTitle(java.lang.String seoTitle) {
		set("seo_title", seoTitle);
		return (M)this;
	}

	public java.lang.String getSeoTitle() {
		return get("seo_title");
	}

	public M setTreePath(java.lang.String treePath) {
		set("tree_path", treePath);
		return (M)this;
	}

	public java.lang.String getTreePath() {
		return get("tree_path");
	}

	public M setParent(java.lang.Long parent) {
		set("parent", parent);
		return (M)this;
	}

	public java.lang.Long getParent() {
		return get("parent");
	}

}
