package com.yctxkj.blog.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseLog<M extends BaseLog<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
		return (M)this;
	}

	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public M setIp(java.lang.String ip) {
		set("ip", ip);
		return (M)this;
	}

	public java.lang.String getIp() {
		return get("ip");
	}

	public M setOperation(java.lang.String operation) {
		set("operation", operation);
		return (M)this;
	}

	public java.lang.String getOperation() {
		return get("operation");
	}

	public M setOperator(java.lang.String operator) {
		set("operator", operator);
		return (M)this;
	}

	public java.lang.String getOperator() {
		return get("operator");
	}

	public M setParameter(java.lang.String parameter) {
		set("parameter", parameter);
		return (M)this;
	}

	public java.lang.String getParameter() {
		return get("parameter");
	}

	public M setLevel(java.lang.Integer level) {
		set("level", level);
		return (M)this;
	}

	public java.lang.Integer getLevel() {
		return get("level");
	}

	public M setIpregion(java.lang.String ipregion) {
		set("ipregion", ipregion);
		return (M)this;
	}

	public java.lang.String getIpregion() {
		return get("ipregion");
	}

	public M setLogtype(java.lang.String logtype) {
		set("logtype", logtype);
		return (M)this;
	}

	public java.lang.String getLogtype() {
		return get("logtype");
	}

	public M setUrl(java.lang.String url) {
		set("url", url);
		return (M)this;
	}

	public java.lang.String getUrl() {
		return get("url");
	}

}
