package com.yctxkj.blog.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseArticle<M extends BaseArticle<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
		return (M)this;
	}

	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

	public M setSummary(java.lang.String summary) {
		set("summary", summary);
		return (M)this;
	}

	public java.lang.String getSummary() {
		return get("summary");
	}

	public M setAuthor(java.lang.String author) {
		set("author", author);
		return (M)this;
	}

	public java.lang.String getAuthor() {
		return get("author");
	}

	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public M setHits(java.lang.Long hits) {
		set("hits", hits);
		return (M)this;
	}

	public java.lang.Long getHits() {
		return get("hits");
	}

	public M setIsPublication(java.lang.Boolean isPublication) {
		set("is_publication", isPublication);
		return (M)this;
	}

	public java.lang.Boolean getIsPublication() {
		return get("is_publication");
	}

	public M setIsTop(java.lang.Boolean isTop) {
		set("is_top", isTop);
		return (M)this;
	}

	public java.lang.Boolean getIsTop() {
		return get("is_top");
	}

	public M setSeoDescription(java.lang.String seoDescription) {
		set("seo_description", seoDescription);
		return (M)this;
	}

	public java.lang.String getSeoDescription() {
		return get("seo_description");
	}

	public M setSeoKeywords(java.lang.String seoKeywords) {
		set("seo_keywords", seoKeywords);
		return (M)this;
	}

	public java.lang.String getSeoKeywords() {
		return get("seo_keywords");
	}

	public M setSeoTitle(java.lang.String seoTitle) {
		set("seo_title", seoTitle);
		return (M)this;
	}

	public java.lang.String getSeoTitle() {
		return get("seo_title");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public M setArticleCategory(java.lang.Long articleCategory) {
		set("article_category", articleCategory);
		return (M)this;
	}

	public java.lang.Long getArticleCategory() {
		return get("article_category");
	}

}
