package com.yctxkj.blog.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("xx_admin", "id", Admin.class);
		arp.addMapping("xx_article", "id", Article.class);
		arp.addMapping("xx_article_category", "id", ArticleCategory.class);
		arp.addMapping("xx_friend_link", "id", FriendLink.class);
		arp.addMapping("xx_log", "id", Log.class);
	}
}

