package com.yctxkj.blog.model;

import com.yctxkj.blog.model.base.BaseArticleCategory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ArticleCategory extends BaseArticleCategory<ArticleCategory> {
	public static final ArticleCategory dao = new ArticleCategory().dao();
	
	
}
