package com.yctxkj.blog.model;

import com.yctxkj.blog.model.base.BaseArticle;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Article extends BaseArticle<Article> {
	public static final Article dao = new Article().dao();
	
	
}
