package com.yctxkj.blog.model;

import com.yctxkj.blog.model.base.BaseFriendLink;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FriendLink extends BaseFriendLink<FriendLink> {
	public static final FriendLink dao = new FriendLink().dao();
}
