package com.yctxkj.blog.model;

import com.yctxkj.blog.model.base.BaseLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Log extends BaseLog<Log> {
	public static final Log dao = new Log().dao();
}
